export interface Specialty {
  id: string
  name: string
  category: 'surgical' | 'medical' | 'diagnostic' | 'support'
  description: string
  dayInLife: string
  avgSalary: number
  salaryRange: [number, number]
  residencyLength: number // years
  fellowshipLength?: number
  matchRate2024: number // percent of applicants who matched
  avgStepScore: number // avg Step 2 CK
  competitiveness: 1 | 2 | 3 | 4 | 5 // 5 = most competitive
  lifestyle: 1 | 2 | 3 | 4 | 5 // 5 = best lifestyle
  researchImportance: 1 | 2 | 3 | 4 | 5
  patientContact: 1 | 2 | 3 | 4 | 5 // 5 = most
  procedural: 1 | 2 | 3 | 4 | 5 // 5 = most procedural
  avgHoursPerWeek: number
  callFrequency: string
  burnoutRate: number // percent
  genderDistribution: { male: number; female: number }
  medianAge: number
  growthOutlook: 'declining' | 'stable' | 'growing' | 'rapid-growth'
  positions2024: number // total positions offered
  imgFriendly: boolean
  topFellowships: string[]
  relatedSpecialties: string[]
  tags: string[]
}

export const specialties: Specialty[] = [
  {
    id: 'internal-medicine',
    name: 'Internal Medicine',
    category: 'medical',
    description: 'Internal medicine physicians diagnose and treat complex adult diseases. They serve as primary care doctors or subspecialize in areas like cardiology, gastroenterology, or pulmonology.',
    dayInLife: 'Rounding on hospitalized patients, clinic visits for chronic disease management, interpreting labs and imaging, coordinating multidisciplinary care.',
    avgSalary: 273000,
    salaryRange: [210000, 385000],
    residencyLength: 3,
    matchRate2024: 93.5,
    avgStepScore: 230,
    competitiveness: 2,
    lifestyle: 3,
    researchImportance: 2,
    patientContact: 5,
    procedural: 2,
    avgHoursPerWeek: 55,
    callFrequency: 'Every 4-6 days (residency), varies attending',
    burnoutRate: 49,
    genderDistribution: { male: 54, female: 46 },
    medianAge: 48,
    growthOutlook: 'growing',
    positions2024: 9200,
    imgFriendly: true,
    topFellowships: ['Cardiology', 'Gastroenterology', 'Pulmonary/Critical Care', 'Hematology/Oncology', 'Endocrinology', 'Rheumatology', 'Nephrology', 'Infectious Disease'],
    relatedSpecialties: ['family-medicine', 'hospitalist-medicine', 'geriatrics'],
    tags: ['primary-care-option', 'many-subspecialties', 'high-demand', 'img-friendly']
  },
  {
    id: 'surgery-general',
    name: 'General Surgery',
    category: 'surgical',
    description: 'General surgeons operate on the abdominal organs, thyroid, breast, skin, and soft tissues. The field offers broad operative experience and serves as a gateway to many surgical subspecialties.',
    dayInLife: 'Early morning rounds, operating room cases (hernias, cholecystectomies, appendectomies, trauma), afternoon clinic, evening call coverage.',
    avgSalary: 402000,
    salaryRange: [310000, 550000],
    residencyLength: 5,
    matchRate2024: 83.2,
    avgStepScore: 243,
    competitiveness: 4,
    lifestyle: 1,
    researchImportance: 3,
    patientContact: 3,
    procedural: 5,
    avgHoursPerWeek: 65,
    callFrequency: 'Every 3-4 days, home call as attending',
    burnoutRate: 53,
    genderDistribution: { male: 68, female: 32 },
    medianAge: 50,
    growthOutlook: 'stable',
    positions2024: 1450,
    imgFriendly: false,
    topFellowships: ['Surgical Oncology', 'Trauma/Critical Care', 'Minimally Invasive', 'Colorectal Surgery', 'Transplant Surgery'],
    relatedSpecialties: ['orthopedic-surgery', 'vascular-surgery', 'urology'],
    tags: ['surgical', 'long-residency', 'high-earning', 'demanding-lifestyle']
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    category: 'medical',
    description: 'Pediatricians provide medical care for infants, children, and adolescents. The field emphasizes developmental milestones, preventive care, and family-centered medicine.',
    dayInLife: 'Well-child visits, sick visits, managing childhood illnesses, counseling families, developmental screening, coordinating care with specialists.',
    avgSalary: 240000,
    salaryRange: [190000, 310000],
    residencyLength: 3,
    matchRate2024: 90.1,
    avgStepScore: 226,
    competitiveness: 2,
    lifestyle: 4,
    researchImportance: 2,
    patientContact: 5,
    procedural: 1,
    avgHoursPerWeek: 50,
    callFrequency: 'Every 4-6 days (residency), light as attending',
    burnoutRate: 44,
    genderDistribution: { male: 32, female: 68 },
    medianAge: 46,
    growthOutlook: 'growing',
    positions2024: 2900,
    imgFriendly: true,
    topFellowships: ['Pediatric Cardiology', 'Neonatology', 'Pediatric Hematology/Oncology', 'Pediatric Emergency Medicine', 'Pediatric Gastroenterology'],
    relatedSpecialties: ['family-medicine', 'internal-medicine', 'child-psychiatry'],
    tags: ['primary-care', 'good-lifestyle', 'family-focused', 'img-friendly']
  },
  {
    id: 'emergency-medicine',
    name: 'Emergency Medicine',
    category: 'medical',
    description: 'Emergency physicians evaluate and stabilize patients with acute illnesses and injuries in the emergency department. The field requires rapid decision-making across all organ systems.',
    dayInLife: 'Shift-based work (8-12 hour shifts), managing trauma, chest pain, strokes, pediatric emergencies, procedures (intubation, central lines, laceration repair).',
    avgSalary: 350000,
    salaryRange: [270000, 430000],
    residencyLength: 3,
    matchRate2024: 82.5,
    avgStepScore: 237,
    competitiveness: 3,
    lifestyle: 3,
    researchImportance: 2,
    patientContact: 5,
    procedural: 4,
    avgHoursPerWeek: 42,
    callFrequency: 'No traditional call — shift-based',
    burnoutRate: 60,
    genderDistribution: { male: 62, female: 38 },
    medianAge: 44,
    growthOutlook: 'stable',
    positions2024: 2700,
    imgFriendly: false,
    topFellowships: ['Ultrasound', 'Toxicology', 'EMS', 'Sports Medicine', 'Critical Care'],
    relatedSpecialties: ['critical-care', 'trauma-surgery', 'anesthesiology'],
    tags: ['shift-work', 'high-acuity', 'procedural', 'no-call']
  },
  {
    id: 'family-medicine',
    name: 'Family Medicine',
    category: 'medical',
    description: 'Family physicians provide comprehensive care to patients of all ages. They handle everything from pediatrics to geriatrics, obstetrics to minor procedures, making them the most versatile doctors.',
    dayInLife: 'Clinic visits spanning all ages, managing chronic diseases, preventive care, minor procedures (biopsies, joint injections), some obstetric care.',
    avgSalary: 255000,
    salaryRange: [200000, 330000],
    residencyLength: 3,
    matchRate2024: 92.8,
    avgStepScore: 222,
    competitiveness: 1,
    lifestyle: 4,
    researchImportance: 1,
    patientContact: 5,
    procedural: 2,
    avgHoursPerWeek: 47,
    callFrequency: 'Light — varies by practice',
    burnoutRate: 46,
    genderDistribution: { male: 42, female: 58 },
    medianAge: 47,
    growthOutlook: 'rapid-growth',
    positions2024: 4600,
    imgFriendly: true,
    topFellowships: ['Sports Medicine', 'Geriatrics', 'Hospice & Palliative', 'Obstetrics', 'Addiction Medicine'],
    relatedSpecialties: ['internal-medicine', 'pediatrics', 'obstetrics-gynecology'],
    tags: ['primary-care', 'versatile', 'high-demand', 'rural-options', 'img-friendly']
  },
  {
    id: 'orthopedic-surgery',
    name: 'Orthopedic Surgery',
    category: 'surgical',
    description: 'Orthopedic surgeons treat musculoskeletal conditions including fractures, sports injuries, joint replacements, spinal disorders, and congenital deformities.',
    dayInLife: 'Operating room (joint replacements, fracture fixation, arthroscopy), clinic for post-ops and new evaluations, reading imaging, casting/splinting.',
    avgSalary: 558000,
    salaryRange: [400000, 780000],
    residencyLength: 5,
    matchRate2024: 72.5,
    avgStepScore: 252,
    competitiveness: 5,
    lifestyle: 2,
    researchImportance: 4,
    patientContact: 3,
    procedural: 5,
    avgHoursPerWeek: 60,
    callFrequency: 'Every 3-5 days for trauma coverage',
    burnoutRate: 42,
    genderDistribution: { male: 84, female: 16 },
    medianAge: 51,
    growthOutlook: 'growing',
    positions2024: 870,
    imgFriendly: false,
    topFellowships: ['Sports Medicine', 'Spine Surgery', 'Hand Surgery', 'Trauma', 'Pediatric Orthopedics', 'Joint Reconstruction'],
    relatedSpecialties: ['surgery-general', 'sports-medicine', 'physical-medicine'],
    tags: ['surgical', 'highest-paying', 'very-competitive', 'sports']
  },
  {
    id: 'dermatology',
    name: 'Dermatology',
    category: 'medical',
    description: 'Dermatologists diagnose and treat conditions of the skin, hair, and nails. The field combines medical management, procedures, and pathology with one of the best lifestyles in medicine.',
    dayInLife: 'Clinic-based: skin exams, biopsies, cryotherapy, acne management, skin cancer screening, cosmetic procedures. Mostly outpatient with minimal call.',
    avgSalary: 455000,
    salaryRange: [350000, 650000],
    residencyLength: 4,
    matchRate2024: 68.9,
    avgStepScore: 254,
    competitiveness: 5,
    lifestyle: 5,
    researchImportance: 4,
    patientContact: 4,
    procedural: 3,
    avgHoursPerWeek: 43,
    callFrequency: 'Rare — mostly clinic hours',
    burnoutRate: 32,
    genderDistribution: { male: 42, female: 58 },
    medianAge: 49,
    growthOutlook: 'growing',
    positions2024: 560,
    imgFriendly: false,
    topFellowships: ['Mohs Surgery', 'Dermatopathology', 'Pediatric Dermatology', 'Cosmetic Dermatology'],
    relatedSpecialties: ['plastic-surgery', 'allergy-immunology'],
    tags: ['best-lifestyle', 'very-competitive', 'outpatient', 'cosmetic-option']
  },
  {
    id: 'anesthesiology',
    name: 'Anesthesiology',
    category: 'support',
    description: 'Anesthesiologists manage perioperative care, pain management, and critical care. They administer anesthesia for surgeries and procedures and are experts in airway management and hemodynamic monitoring.',
    dayInLife: 'Pre-op evaluations, administering general/regional anesthesia, monitoring patients during surgery, managing pain clinic, ICU coverage.',
    avgSalary: 405000,
    salaryRange: [320000, 510000],
    residencyLength: 4,
    matchRate2024: 89.3,
    avgStepScore: 240,
    competitiveness: 3,
    lifestyle: 3,
    researchImportance: 2,
    patientContact: 2,
    procedural: 5,
    avgHoursPerWeek: 55,
    callFrequency: 'Every 4-6 days, 24h calls common in residency',
    burnoutRate: 50,
    genderDistribution: { male: 63, female: 37 },
    medianAge: 50,
    growthOutlook: 'stable',
    positions2024: 1850,
    imgFriendly: true,
    topFellowships: ['Pain Medicine', 'Critical Care', 'Cardiac Anesthesia', 'Pediatric Anesthesia', 'Regional Anesthesia'],
    relatedSpecialties: ['critical-care', 'emergency-medicine', 'pain-medicine'],
    tags: ['procedural', 'operating-room', 'good-salary', 'img-friendly']
  },
  {
    id: 'psychiatry',
    name: 'Psychiatry',
    category: 'medical',
    description: 'Psychiatrists diagnose and treat mental health disorders using therapy, medications, and other interventions. Growing demand and the mental health crisis have made this field increasingly vital.',
    dayInLife: 'Patient assessments, medication management, therapy sessions, consult-liaison in hospitals, emergency psychiatric evaluations.',
    avgSalary: 287000,
    salaryRange: [220000, 380000],
    residencyLength: 4,
    matchRate2024: 91.2,
    avgStepScore: 228,
    competitiveness: 2,
    lifestyle: 4,
    researchImportance: 2,
    patientContact: 5,
    procedural: 1,
    avgHoursPerWeek: 48,
    callFrequency: 'Light — varies, some weekend on-call',
    burnoutRate: 42,
    genderDistribution: { male: 43, female: 57 },
    medianAge: 48,
    growthOutlook: 'rapid-growth',
    positions2024: 2100,
    imgFriendly: true,
    topFellowships: ['Child & Adolescent', 'Addiction Psychiatry', 'Forensic Psychiatry', 'Geriatric Psychiatry', 'Consultation-Liaison'],
    relatedSpecialties: ['neurology', 'family-medicine', 'internal-medicine'],
    tags: ['growing-demand', 'good-lifestyle', 'mental-health', 'img-friendly', 'telepsych']
  },
  {
    id: 'radiology',
    name: 'Radiology',
    category: 'diagnostic',
    description: 'Radiologists interpret medical images (X-rays, CT, MRI, ultrasound) to diagnose diseases. Interventional radiologists perform minimally invasive image-guided procedures.',
    dayInLife: 'Reading imaging studies (CT, MRI, X-ray, US), dictating reports, consulting with clinical teams, performing fluoroscopy or IR procedures.',
    avgSalary: 427000,
    salaryRange: [340000, 560000],
    residencyLength: 5,
    matchRate2024: 85.7,
    avgStepScore: 248,
    competitiveness: 4,
    lifestyle: 4,
    researchImportance: 3,
    patientContact: 1,
    procedural: 3,
    avgHoursPerWeek: 50,
    callFrequency: 'Nighthawk/overnight reading, weekend coverage',
    burnoutRate: 38,
    genderDistribution: { male: 72, female: 28 },
    medianAge: 52,
    growthOutlook: 'stable',
    positions2024: 1100,
    imgFriendly: false,
    topFellowships: ['Interventional Radiology', 'Neuroradiology', 'Musculoskeletal', 'Body Imaging', 'Breast Imaging', 'Nuclear Medicine'],
    relatedSpecialties: ['nuclear-medicine', 'radiation-oncology'],
    tags: ['diagnostic', 'good-lifestyle', 'technology', 'remote-work-potential']
  },
  {
    id: 'obstetrics-gynecology',
    name: 'Obstetrics & Gynecology',
    category: 'surgical',
    description: 'OB/GYN physicians provide reproductive healthcare, deliver babies, and perform gynecologic surgeries. The field uniquely combines primary care, surgery, and obstetric care.',
    dayInLife: 'Prenatal visits, labor & delivery management, cesarean sections, gynecologic surgeries (hysterectomies, laparoscopies), clinic for well-woman exams.',
    avgSalary: 336000,
    salaryRange: [260000, 440000],
    residencyLength: 4,
    matchRate2024: 88.4,
    avgStepScore: 239,
    competitiveness: 3,
    lifestyle: 2,
    researchImportance: 2,
    patientContact: 5,
    procedural: 4,
    avgHoursPerWeek: 58,
    callFrequency: 'Frequent — labor and delivery coverage 24/7',
    burnoutRate: 51,
    genderDistribution: { male: 18, female: 82 },
    medianAge: 47,
    growthOutlook: 'stable',
    positions2024: 1400,
    imgFriendly: false,
    topFellowships: ['Maternal-Fetal Medicine', 'Gynecologic Oncology', 'Reproductive Endocrinology', 'Female Pelvic Medicine', 'Minimally Invasive Surgery'],
    relatedSpecialties: ['surgery-general', 'family-medicine', 'urology'],
    tags: ['surgical', 'primary-care-option', 'labor-delivery', 'womens-health']
  },
  {
    id: 'neurology',
    name: 'Neurology',
    category: 'medical',
    description: 'Neurologists diagnose and treat disorders of the brain, spinal cord, peripheral nerves, and muscles. The field has been revolutionized by new treatments for stroke, MS, and epilepsy.',
    dayInLife: 'Hospital consults for stroke/seizure, outpatient clinic for MS, Parkinson\'s, headaches, epilepsy management, EEG interpretation, lumbar punctures.',
    avgSalary: 301000,
    salaryRange: [235000, 400000],
    residencyLength: 4,
    matchRate2024: 87.9,
    avgStepScore: 235,
    competitiveness: 3,
    lifestyle: 3,
    researchImportance: 3,
    patientContact: 4,
    procedural: 2,
    avgHoursPerWeek: 52,
    callFrequency: 'Every 4-7 days for stroke call',
    burnoutRate: 45,
    genderDistribution: { male: 52, female: 48 },
    medianAge: 49,
    growthOutlook: 'rapid-growth',
    positions2024: 950,
    imgFriendly: true,
    topFellowships: ['Stroke/Vascular Neurology', 'Epilepsy', 'Neuromuscular', 'Movement Disorders', 'Neuro-oncology', 'Headache Medicine'],
    relatedSpecialties: ['neurosurgery', 'psychiatry', 'physical-medicine'],
    tags: ['growing-field', 'cerebral', 'new-treatments', 'img-friendly']
  },
  {
    id: 'ophthalmology',
    name: 'Ophthalmology',
    category: 'surgical',
    description: 'Ophthalmologists specialize in medical and surgical treatment of eye diseases. They perform procedures like cataract surgery, LASIK, retinal surgery, and manage conditions like glaucoma and macular degeneration.',
    dayInLife: 'Clinic eye exams (slit lamp, fundoscopy), cataract surgeries, laser procedures, retinal injections, managing glaucoma, diabetic eye disease.',
    avgSalary: 379000,
    salaryRange: [280000, 550000],
    residencyLength: 4,
    matchRate2024: 74.2,
    avgStepScore: 250,
    competitiveness: 5,
    lifestyle: 4,
    researchImportance: 4,
    patientContact: 4,
    procedural: 5,
    avgHoursPerWeek: 47,
    callFrequency: 'Light — mostly emergency consults',
    burnoutRate: 30,
    genderDistribution: { male: 58, female: 42 },
    medianAge: 51,
    growthOutlook: 'growing',
    positions2024: 490,
    imgFriendly: false,
    topFellowships: ['Retina', 'Glaucoma', 'Cornea', 'Oculoplastics', 'Pediatric Ophthalmology', 'Neuro-ophthalmology'],
    relatedSpecialties: ['dermatology', 'otolaryngology'],
    tags: ['surgical', 'good-lifestyle', 'very-competitive', 'microsurgery']
  },
  {
    id: 'pathology',
    name: 'Pathology',
    category: 'diagnostic',
    description: 'Pathologists examine tissues, cells, and body fluids to diagnose disease. They are the "doctor\'s doctor" — virtually every diagnosis passes through pathology.',
    dayInLife: 'Microscope work (surgical pathology, cytology), autopsy, frozen section reads during surgery, blood bank oversight, molecular testing review.',
    avgSalary: 316000,
    salaryRange: [245000, 410000],
    residencyLength: 4,
    matchRate2024: 85.1,
    avgStepScore: 233,
    competitiveness: 2,
    lifestyle: 4,
    researchImportance: 3,
    patientContact: 1,
    procedural: 2,
    avgHoursPerWeek: 45,
    callFrequency: 'Light — frozen section call, blood bank',
    burnoutRate: 34,
    genderDistribution: { male: 50, female: 50 },
    medianAge: 52,
    growthOutlook: 'stable',
    positions2024: 600,
    imgFriendly: true,
    topFellowships: ['Dermatopathology', 'Hematopathology', 'Neuropathology', 'Molecular Genetic Pathology', 'Forensic Pathology', 'Cytopathology'],
    relatedSpecialties: ['radiology', 'laboratory-medicine'],
    tags: ['diagnostic', 'minimal-patient-contact', 'intellectual', 'img-friendly']
  },
  {
    id: 'plastic-surgery',
    name: 'Plastic Surgery',
    category: 'surgical',
    description: 'Plastic surgeons reconstruct and repair tissues damaged by trauma, disease, or congenital defects, and perform aesthetic procedures. The field spans hand surgery, microsurgery, burns, and cosmetics.',
    dayInLife: 'Operating room (reconstruction, cosmetic procedures, hand surgery, burn care), clinic consultations, post-op follow-ups.',
    avgSalary: 501000,
    salaryRange: [350000, 800000],
    residencyLength: 6,
    matchRate2024: 61.3,
    avgStepScore: 255,
    competitiveness: 5,
    lifestyle: 3,
    researchImportance: 5,
    patientContact: 4,
    procedural: 5,
    avgHoursPerWeek: 55,
    callFrequency: 'Varies — hand/trauma call in academic settings',
    burnoutRate: 35,
    genderDistribution: { male: 67, female: 33 },
    medianAge: 48,
    growthOutlook: 'growing',
    positions2024: 221,
    imgFriendly: false,
    topFellowships: ['Hand Surgery', 'Craniofacial', 'Microsurgery', 'Burn Surgery', 'Aesthetic Surgery'],
    relatedSpecialties: ['surgery-general', 'orthopedic-surgery', 'otolaryngology'],
    tags: ['most-competitive', 'surgical', 'cosmetic-option', 'high-earning']
  },
  {
    id: 'neurosurgery',
    name: 'Neurosurgery',
    category: 'surgical',
    description: 'Neurosurgeons operate on the brain, spinal cord, and peripheral nerves. One of the longest and most demanding training paths in medicine, but among the highest-paying specialties.',
    dayInLife: 'Long operating days (brain tumor resections, spine fusions, aneurysm clipping), ICU rounding on neurosurgical patients, clinic, emergency cases.',
    avgSalary: 646000,
    salaryRange: [450000, 900000],
    residencyLength: 7,
    matchRate2024: 73.8,
    avgStepScore: 252,
    competitiveness: 5,
    lifestyle: 1,
    researchImportance: 5,
    patientContact: 3,
    procedural: 5,
    avgHoursPerWeek: 70,
    callFrequency: 'Frequent — emergency neurosurgical coverage',
    burnoutRate: 57,
    genderDistribution: { male: 82, female: 18 },
    medianAge: 52,
    growthOutlook: 'stable',
    positions2024: 240,
    imgFriendly: false,
    topFellowships: ['Spine', 'Neuro-oncology', 'Pediatric Neurosurgery', 'Cerebrovascular', 'Functional Neurosurgery', 'Skull Base'],
    relatedSpecialties: ['neurology', 'orthopedic-surgery', 'surgery-general'],
    tags: ['most-competitive', 'highest-paying', 'longest-training', 'surgical']
  },
  {
    id: 'otolaryngology',
    name: 'Otolaryngology (ENT)',
    category: 'surgical',
    description: 'ENT surgeons treat conditions of the ear, nose, throat, head, and neck. The field combines medical management with delicate surgical procedures across a wide age range.',
    dayInLife: 'Clinic (sinus evaluations, hearing tests, voice disorders), operating room (tonsillectomies, sinus surgery, thyroid surgery, head & neck cancer), endoscopy.',
    avgSalary: 416000,
    salaryRange: [310000, 560000],
    residencyLength: 5,
    matchRate2024: 75.1,
    avgStepScore: 251,
    competitiveness: 5,
    lifestyle: 3,
    researchImportance: 4,
    patientContact: 4,
    procedural: 5,
    avgHoursPerWeek: 55,
    callFrequency: 'Moderate — airway/bleeding emergencies',
    burnoutRate: 36,
    genderDistribution: { male: 66, female: 34 },
    medianAge: 50,
    growthOutlook: 'stable',
    positions2024: 360,
    imgFriendly: false,
    topFellowships: ['Head & Neck Oncology', 'Rhinology', 'Otology/Neurotology', 'Laryngology', 'Pediatric ENT', 'Facial Plastics'],
    relatedSpecialties: ['plastic-surgery', 'surgery-general', 'ophthalmology'],
    tags: ['surgical', 'competitive', 'diverse-procedures', 'head-neck']
  },
  {
    id: 'urology',
    name: 'Urology',
    category: 'surgical',
    description: 'Urologists treat conditions of the urinary tract and male reproductive system. The field includes robotic surgery, oncology, pediatrics, and male infertility.',
    dayInLife: 'Robotic prostatectomies, cystoscopies, kidney stone procedures, clinic for BPH/cancer follow-up, pediatric urology cases.',
    avgSalary: 461000,
    salaryRange: [340000, 620000],
    residencyLength: 6,
    matchRate2024: 78.4,
    avgStepScore: 249,
    competitiveness: 4,
    lifestyle: 3,
    researchImportance: 3,
    patientContact: 4,
    procedural: 5,
    avgHoursPerWeek: 55,
    callFrequency: 'Every 4-5 days for emergencies',
    burnoutRate: 40,
    genderDistribution: { male: 79, female: 21 },
    medianAge: 51,
    growthOutlook: 'growing',
    positions2024: 370,
    imgFriendly: false,
    topFellowships: ['Urologic Oncology', 'Female Pelvic/Reconstructive', 'Pediatric Urology', 'Male Infertility', 'Endourology'],
    relatedSpecialties: ['surgery-general', 'obstetrics-gynecology', 'nephrology'],
    tags: ['surgical', 'robotic-surgery', 'competitive', 'good-earnings']
  },
  {
    id: 'physical-medicine',
    name: 'Physical Medicine & Rehabilitation (PM&R)',
    category: 'medical',
    description: 'PM&R physicians (physiatrists) restore function for patients with disabilities from injuries, illness, or congenital conditions. They focus on quality of life without surgery.',
    dayInLife: 'Inpatient rehab rounding (stroke, spinal cord injury, TBI patients), outpatient musculoskeletal clinic, injections, electrodiagnostic studies.',
    avgSalary: 275000,
    salaryRange: [210000, 370000],
    residencyLength: 4,
    matchRate2024: 86.5,
    avgStepScore: 229,
    competitiveness: 2,
    lifestyle: 4,
    researchImportance: 2,
    patientContact: 5,
    procedural: 3,
    avgHoursPerWeek: 48,
    callFrequency: 'Light — rehab unit coverage',
    burnoutRate: 38,
    genderDistribution: { male: 55, female: 45 },
    medianAge: 48,
    growthOutlook: 'growing',
    positions2024: 510,
    imgFriendly: true,
    topFellowships: ['Pain Medicine', 'Sports Medicine', 'Spinal Cord Injury', 'Brain Injury', 'Neuromuscular'],
    relatedSpecialties: ['neurology', 'orthopedic-surgery', 'sports-medicine'],
    tags: ['good-lifestyle', 'rehabilitation', 'functional-medicine', 'img-friendly']
  },
  {
    id: 'radiation-oncology',
    name: 'Radiation Oncology',
    category: 'medical',
    description: 'Radiation oncologists use targeted radiation therapy to treat cancer. They combine physics, biology, and medicine to design treatment plans for tumor destruction.',
    dayInLife: 'Treatment planning with physicists, seeing patients on treatment, new consults, tumor boards, follow-up clinics, simulation sessions.',
    avgSalary: 418000,
    salaryRange: [310000, 550000],
    residencyLength: 5,
    matchRate2024: 79.3,
    avgStepScore: 244,
    competitiveness: 3,
    lifestyle: 4,
    researchImportance: 4,
    patientContact: 4,
    procedural: 2,
    avgHoursPerWeek: 50,
    callFrequency: 'Light — occasional weekend coverage',
    burnoutRate: 37,
    genderDistribution: { male: 60, female: 40 },
    medianAge: 50,
    growthOutlook: 'stable',
    positions2024: 200,
    imgFriendly: false,
    topFellowships: ['Brachytherapy', 'Proton Therapy', 'Stereotactic Radiosurgery'],
    relatedSpecialties: ['medical-oncology', 'radiology', 'nuclear-medicine'],
    tags: ['cancer-care', 'technology', 'good-lifestyle', 'small-field']
  },
]

// Utility functions
export function getSpecialtyById(id: string): Specialty | undefined {
  return specialties.find(s => s.id === id)
}

export function getSpecialtiesByCategory(category: Specialty['category']): Specialty[] {
  return specialties.filter(s => s.category === category)
}

export function formatSalary(amount: number): string {
  return `$${(amount / 1000).toFixed(0)}K`
}

export function getCompetitivenessLabel(level: number): string {
  const labels = ['', 'Low', 'Moderate', 'Competitive', 'Highly Competitive', 'Ultra Competitive']
  return labels[level]
}

export function getLifestyleLabel(level: number): string {
  const labels = ['', 'Very Demanding', 'Demanding', 'Moderate', 'Good', 'Excellent']
  return labels[level]
}
