export interface SpecialtyData {
  name: string;
  category: string;
  residencyYears: number;
  fellowshipYears: number;
  totalTrainingYears: number;
  residentSalaryYear1: number;
  residentAnnualRaise: number;
  fellowSalaryYear1: number;
  attendingSalaryYear1: number;
  attendingSalaryGrowthRate: number;
  attendingSalaryCap: number;
  moonlightingIncome: number;
  signingBonus: number;
  malpracticeInsurance: number;
}

export const SPECIALTIES: Record<string, SpecialtyData> = {
  "emergency-medicine": {
    name: "Emergency Medicine",
    category: "Primary / Acute Care",
    residencyYears: 3,
    fellowshipYears: 0,
    totalTrainingYears: 3,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 350000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 500000,
    moonlightingIncome: 15000,
    signingBonus: 50000,
    malpracticeInsurance: 15000,
  },
  "internal-medicine": {
    name: "Internal Medicine",
    category: "Primary / Acute Care",
    residencyYears: 3,
    fellowshipYears: 0,
    totalTrainingYears: 3,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 270000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 400000,
    moonlightingIncome: 10000,
    signingBonus: 30000,
    malpracticeInsurance: 10000,
  },
  "family-medicine": {
    name: "Family Medicine",
    category: "Primary / Acute Care",
    residencyYears: 3,
    fellowshipYears: 0,
    totalTrainingYears: 3,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 250000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 380000,
    moonlightingIncome: 8000,
    signingBonus: 35000,
    malpracticeInsurance: 8000,
  },
  "pediatrics": {
    name: "Pediatrics",
    category: "Primary / Acute Care",
    residencyYears: 3,
    fellowshipYears: 0,
    totalTrainingYears: 3,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 240000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 360000,
    moonlightingIncome: 5000,
    signingBonus: 25000,
    malpracticeInsurance: 10000,
  },
  "cardiology": {
    name: "Cardiology",
    category: "Internal Medicine Subspecialty",
    residencyYears: 3,
    fellowshipYears: 3,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 500000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 750000,
    moonlightingIncome: 10000,
    signingBonus: 50000,
    malpracticeInsurance: 20000,
  },
  "interventional-cardiology": {
    name: "Interventional Cardiology",
    category: "Internal Medicine Subspecialty",
    residencyYears: 3,
    fellowshipYears: 4,
    totalTrainingYears: 7,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 600000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 900000,
    moonlightingIncome: 10000,
    signingBonus: 75000,
    malpracticeInsurance: 25000,
  },
  "gastroenterology": {
    name: "Gastroenterology",
    category: "Internal Medicine Subspecialty",
    residencyYears: 3,
    fellowshipYears: 3,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 490000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 700000,
    moonlightingIncome: 8000,
    signingBonus: 50000,
    malpracticeInsurance: 18000,
  },
  "pulm-critical-care": {
    name: "Pulm / Critical Care",
    category: "Internal Medicine Subspecialty",
    residencyYears: 3,
    fellowshipYears: 3,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 420000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 600000,
    moonlightingIncome: 10000,
    signingBonus: 40000,
    malpracticeInsurance: 15000,
  },
  "hematology-oncology": {
    name: "Hematology / Oncology",
    category: "Internal Medicine Subspecialty",
    residencyYears: 3,
    fellowshipYears: 3,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 440000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 650000,
    moonlightingIncome: 5000,
    signingBonus: 40000,
    malpracticeInsurance: 15000,
  },
  "general-surgery": {
    name: "General Surgery",
    category: "Surgical",
    residencyYears: 5,
    fellowshipYears: 0,
    totalTrainingYears: 5,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 420000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 600000,
    moonlightingIncome: 0,
    signingBonus: 50000,
    malpracticeInsurance: 35000,
  },
  "orthopedic-surgery": {
    name: "Orthopedic Surgery",
    category: "Surgical",
    residencyYears: 5,
    fellowshipYears: 1,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 600000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 900000,
    moonlightingIncome: 0,
    signingBonus: 75000,
    malpracticeInsurance: 40000,
  },
  "neurosurgery": {
    name: "Neurosurgery",
    category: "Surgical",
    residencyYears: 7,
    fellowshipYears: 1,
    totalTrainingYears: 8,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 700000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 1100000,
    moonlightingIncome: 0,
    signingBonus: 100000,
    malpracticeInsurance: 60000,
  },
  "ct-surgery": {
    name: "Cardiothoracic Surgery",
    category: "Surgical",
    residencyYears: 5,
    fellowshipYears: 3,
    totalTrainingYears: 8,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 600000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 900000,
    moonlightingIncome: 0,
    signingBonus: 75000,
    malpracticeInsurance: 50000,
  },
  "plastic-surgery": {
    name: "Plastic Surgery",
    category: "Surgical",
    residencyYears: 6,
    fellowshipYears: 0,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 480000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 750000,
    moonlightingIncome: 0,
    signingBonus: 50000,
    malpracticeInsurance: 30000,
  },
  "urology": {
    name: "Urology",
    category: "Surgical",
    residencyYears: 5,
    fellowshipYears: 1,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 470000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 700000,
    moonlightingIncome: 0,
    signingBonus: 50000,
    malpracticeInsurance: 25000,
  },
  "dermatology": {
    name: "Dermatology",
    category: "Other Specialty",
    residencyYears: 4,
    fellowshipYears: 0,
    totalTrainingYears: 4,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 450000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 700000,
    moonlightingIncome: 5000,
    signingBonus: 50000,
    malpracticeInsurance: 10000,
  },
  "radiology": {
    name: "Radiology",
    category: "Other Specialty",
    residencyYears: 5,
    fellowshipYears: 1,
    totalTrainingYears: 6,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 75000,
    attendingSalaryYear1: 450000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 650000,
    moonlightingIncome: 5000,
    signingBonus: 50000,
    malpracticeInsurance: 15000,
  },
  "anesthesiology": {
    name: "Anesthesiology",
    category: "Other Specialty",
    residencyYears: 4,
    fellowshipYears: 0,
    totalTrainingYears: 4,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 400000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 580000,
    moonlightingIncome: 10000,
    signingBonus: 50000,
    malpracticeInsurance: 12000,
  },
  "ophthalmology": {
    name: "Ophthalmology",
    category: "Other Specialty",
    residencyYears: 4,
    fellowshipYears: 0,
    totalTrainingYears: 4,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 380000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 600000,
    moonlightingIncome: 0,
    signingBonus: 40000,
    malpracticeInsurance: 12000,
  },
  "psychiatry": {
    name: "Psychiatry",
    category: "Other Specialty",
    residencyYears: 4,
    fellowshipYears: 0,
    totalTrainingYears: 4,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 280000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 420000,
    moonlightingIncome: 10000,
    signingBonus: 40000,
    malpracticeInsurance: 8000,
  },
  "pm-r": {
    name: "Physical Medicine & Rehab",
    category: "Other Specialty",
    residencyYears: 4,
    fellowshipYears: 0,
    totalTrainingYears: 4,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 300000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 440000,
    moonlightingIncome: 5000,
    signingBonus: 30000,
    malpracticeInsurance: 10000,
  },
  "pathology": {
    name: "Pathology",
    category: "Other Specialty",
    residencyYears: 4,
    fellowshipYears: 1,
    totalTrainingYears: 5,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 70000,
    attendingSalaryYear1: 310000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 450000,
    moonlightingIncome: 0,
    signingBonus: 25000,
    malpracticeInsurance: 8000,
  },
  "ob-gyn": {
    name: "OB/GYN",
    category: "Primary / Acute Care",
    residencyYears: 4,
    fellowshipYears: 0,
    totalTrainingYears: 4,
    residentSalaryYear1: 63000,
    residentAnnualRaise: 0.03,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 320000,
    attendingSalaryGrowthRate: 0.03,
    attendingSalaryCap: 480000,
    moonlightingIncome: 5000,
    signingBonus: 40000,
    malpracticeInsurance: 45000,
  },
  "business-only": {
    name: "Business Only (MD, No Residency)",
    category: "Non-Clinical",
    residencyYears: 0,
    fellowshipYears: 0,
    totalTrainingYears: 0,
    residentSalaryYear1: 0,
    residentAnnualRaise: 0,
    fellowSalaryYear1: 0,
    attendingSalaryYear1: 0,
    attendingSalaryGrowthRate: 0,
    attendingSalaryCap: 0,
    moonlightingIncome: 0,
    signingBonus: 0,
    malpracticeInsurance: 0,
  },
};

export const SPECIALTY_CATEGORIES = [
  "Primary / Acute Care",
  "Internal Medicine Subspecialty",
  "Surgical",
  "Other Specialty",
  "Non-Clinical",
];

export function getSpecialtiesByCategory(): Record<string, SpecialtyData[]> {
  const grouped: Record<string, SpecialtyData[]> = {};
  for (const cat of SPECIALTY_CATEGORIES) {
    grouped[cat] = Object.values(SPECIALTIES).filter((s) => s.category === cat);
  }
  return grouped;
}
